name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -D warnings
      - name: test
        run: cargo test --all

  # 2026-02-11T01:43:59Z :: maddrm219j5z

  # 2026-02-11T01:44:01Z :: kthk3cbuiq5x

  # 2026-02-11T01:44:02Z :: rjpu7rq8rluc

  # 2026-02-11T01:44:03Z :: c8xshlgv1wv1

  # 2026-02-11T01:44:04Z :: 18weniecbic3

  # 2026-02-11T01:44:06Z :: fj0rzu4kepfq

  # 2026-02-11T01:44:06Z :: 7cwduzplg2mb

  # 2026-02-11T01:44:07Z :: tncx9cc576jn

  # 2026-02-11T01:44:07Z :: e7wz4a91kxdz

  # 2026-02-11T01:44:08Z :: inpnabi69l2m

  # 2026-02-11T01:44:08Z :: ffvq28hb03r8

  # 2026-02-11T01:44:08Z :: efuzlzxaadyj

  # 2026-02-11T01:44:09Z :: 1vewvcephqts

  # 2026-02-11T01:44:10Z :: vzfynk1pucoa

  # 2026-02-11T01:44:11Z :: cpu32krkkwmh

  # 2026-02-11T01:44:11Z :: iwg13axox1if

  # 2026-02-11T01:44:11Z :: jhdfnjl910uq
